#! /bin/sh
#
# /etc/init.d/lpi -- startup script for OpenEMRConnect Local Patient Index
#
### BEGIN INIT INFO
# Provides:          lpi
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Should-Start:      $named
# Should-Stop:       $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start LPI
# Description:       Start the OpenEMRConnect Local Patient Index
### END INIT INFO


NAME=lpi
PACKAGE=mpi

CONFIGDIR="/etc/OpenEMRConnect/$NAME/"
PIDFILE="/var/run/$NAME.pid"
RUNTIMEDIR="/var/run/$NAME/"
LOGDIR="/var/log/$NAME"
LOGFILE="$LOGDIR/$NAME.log"
UBERJAR="/opt/OpenEMRConnect/$PACKAGE/$PACKAGE-1.0-SNAPSHOT-jar-with-dependencies.jar"
USER=oecuser
DAEMON="/usr/bin/java"
DAEMON_ARGS="-DconfigDirectory=$CONFIGDIR -DruntimeDirectory=$RUNTIMEDIR -jar $UBERJAR"

if [ ! -d $RUNTIMEDIR ]; then
    mkdir $RUNTIMEDIR;
    chown $USER $RUNTIMEDIR;
fi

if [ ! -d $LOGDIR ]; then
    mkdir $LOGDIR;
    chown $USER $LOGDIR;
fi

case "$1" in
start)
    echo -n "Starting daemon: "$NAME
    start-stop-daemon --start --pidfile "$PIDFILE" --chuid $USER --verbose --make-pidfile --exec "$DAEMON" -- $DAEMON_ARGS >>$LOGFILE 2>&1 &
    echo "."
    ;;

stop)
    echo -n "Stopping daemon: "$NAME
    start-stop-daemon --stop --pidfile "$PIDFILE" --retry=TERM/30/KILL/5
    echo "."
    ;;

status)
    if kill -0 `cat $PIDFILE` > /dev/null 2>&1; then
        echo "$NAME Running"
        exit 0
    else
        echo "$NAME Not running"
        exit 1
    fi
;;

*)
    echo "Usage: "$1" {start|stop|status}"
    exit 1

esac

exit 0
